### ISSUE TITLE
Is the docker hub image up to date? 

### ISSUE THREAD

**Issue by hradec** [GafferHQ/build#14]
I've found you're pushing this build image to docker hub at: https://hub.docker.com/r/gafferhq/build

Since there's a lot of overlap from my Dockerfile in pipeVFX with GafferHQ/build one, I was considering use `FROM gafferhq/build:latest` instead of `FROM centos:centos7` that I'm using today.

Then I could just add the missing packages and wouldn't have to copy it over your bits to mine. 

But the latest image in docker hub is from 3 months ago, so it doesn't seems like you're keeping it up to date!

No big deal... It would just be nice if it was! 

I think I'll actually pull your Dockerfile in the pipeVFX docker image build process, and push it back to my dockerhub as hradec/gaffeHQ_build:<github revision>

**Comment by themissingcow** [comment]
Hey,

Were there any updates in particular you were after?

We maintain that image specifically as our current supported build platform.  Which essentially boils down to wanting a consistent glibc, compiler, docs toolchain, etc...   We had a bunch of issues with sneaky nested dependency updates caused by nested packages a while back, and so we're quite careful to version lock the entire image.  All of our other run-time dependencies are provided at build time so we don't need to update it that often.

We're currently on `gcc 6.1` as of https://vfxplatform.com, but then there was [this fun](https://groups.google.com/forum/m/#!topic/vfx-platform-discuss/_-_CPw1fD3c) as `devtoolset-6` is seemingly deprecated.  Which means that will probably have fun trying to rebuild that image at all at the moment!

'best
Tom

**Comment by hradec** [comment]
>  Were there any updates in particular you were after? 

None at all... I was just wondering since there are changes in this repo that are 2 months old and the dockerhub image is 3 months. But after a more careful examination, I realized those recent changes aren't used in the docker image itself. The actual Dockerfile and the files it uses are older than 4 months, so dockerhub is indeed up to date!

> We maintain that image specifically as our current supported build platform...

Ho yeah... I known! That's actually why I'm interested in use it as a base image, since pipeVFX has the exact same problem. Before starting using Docker, every time I had to build it  would be broken! It was a constant state of "always fixing it" instead of adding new packages/versions to the build. Having your's as a base image improves even more since currently I'm not locking the versions... I'm just "trusting" on the latest centos 7.

> We're currently on gcc 6.1 as of https://vfxplatform.com...

You mean 6.3.1 or actual 6.1? devtoolset-6 is currently giving me 6.3.1 when using centos:latest as a base for my docker image, which seems to be the choice in the vfxplatform. 

I was actually not too happy to see vfxplatform adopting 6.3.1, since it's actually not available from gcc.org at all! The only source code tar file I could find was from centos 7 itself, and it comes with a bunch of patches! Argh... Kinda ugly, in my opinion. 

That's why I also decided to use devtoolset-6 instead of building gcc 6.3.1 in pipeVFX. PipeVFX builds gcc 4.1.2 and 4.8.5 itself, but I decided to not go through the pain of building 6.3.1 now due to all those patches. Funny thing though... devtoolset-6 gcc 6.3.1 WON'T build GCC 4.1.2 or 4.8.5! There's a bug in it that prevents it from building gcc. (at least those versions I tried). 

> but then there was this fun as devtoolset-6 is seemingly deprecated. 

Hooo boy... didn't known about that.

**Comment by themissingcow** [comment]
> Ho yeah... I known! That's actually why I'm interested in use it as a base image, since pipeVFX has the exact same problem. Before starting using Docker, every time I had to build it would be broken! It was a constant state of "always fixing it" instead of adding new packages/versions to the build. Having your's as a base image improves even more since currently I'm not locking the versions... I'm just "trusting" on the latest centos 7.

Ahh cool, glad its of use, we'll keep that in mind. We intend to version up the image as we move up through compilers/etc.. in some wonderful future utopian time, when we can finally use something more modern...

> > We're currently on gcc 6.1 as of https://vfxplatform.com...
> 
> You mean 6.3.1 or actual 6.1? 

Sorry, `6.3.1` - brain-fail 🙃 

> > but then there was this fun as devtoolset-6 is seemingly deprecated.
> 
> Hooo boy... didn't known about that.

Yeah... we should keep that image safe somewhere as I think it wont even re-build now!

**Comment by boberfly** [comment]
Yeah I ran into this, this seems to be working on this line https://github.com/GafferHQ/build/blob/master/Dockerfile#L29:
```
yum install -y centos-release-scl && \
sed -i 's/7/7.6.1810/g; s|^#\s*\(baseurl=http://\)mirror|\1vault|g; /mirrorlist/d' /etc/yum.repos.d/CentOS-SCLo-*.repo && \
yum install -y devtoolset-6 && \
```
Super lame spent too long on figuring that one out, simply setting 7.6.1810 wasn't enough heh.....

**Comment by themissingcow** [comment]
@boberfly Legend, thanks, have been meaning to try and get it rebuilt and updated. This will save a _lot_ of hassle. Much appreciated.

**Comment by themissingcow** [comment]
Thanks again @boberfly John updated this in #28.
